name: prophetie_app
description: "journal app for dreams, thoughts and ideas"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2
  record: 6.0.0
  flutter_svg: ^2.0.9
  speech_to_text: ^7.0.0
  permission_handler: ^12.0.0+1
  file_picker: ^10.1.9
  share_plus: ^11.0.0
  fl_chart: ^1.0.0
  just_audio: ^0.10.3
  shared_preferences: ^2.2.2
  uni_links: ^0.5.1
  sign_in_with_apple: ^7.0.1
  flutter_dotenv: ^5.1.0
  flutter_speed_dial: ^7.0.0
  encrypt: ^5.0.3
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.4.0
  url_launcher: ^6.2.5
  connectivity_plus: ^4.0.0
  in_app_purchase: 3.2.3
  image_picker: ^1.0.4
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  google_sign_in: ^6.3.0
  audio_waveforms: ^1.0.4  
  intl: ^0.20.2
  cloud_functions: ^5.5.2
  confetti: ^0.6.0
  cached_network_image: ^3.2.3
  flutter_slidable: ^3.0.1
  provider: ^6.0.5 
  video_player: ^2.7.0
  chewie: ^1.7.0
  font_awesome_flutter: ^10.7.0
  
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_ausgefuellt.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/data/traeume_lexikon.json


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
