name: prophetie_app
description: "journal app for dreams, thoughts and ideas"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.9
  path_provider: ^2.1.3
  record: ^6.0.1
  flutter_svg: ^2.0.10
  speech_to_text: ^7.0.1
  permission_handler: ^12.0.1
  file_picker: ^10.2.0
  share_plus: ^11.0.1
  just_audio: ^0.10.4
  shared_preferences: ^2.2.3
  uni_links: ^0.5.2
  sign_in_with_apple: ^7.0.2
  flutter_dotenv: ^5.1.1
  flutter_speed_dial: ^7.0.1
  encrypt: ^5.0.4
  googleapis: ^14.1.0
  googleapis_auth: ^2.0.1
  http: ^1.4.1
  url_launcher: ^6.3.0
  connectivity_plus: ^4.0.2
  in_app_purchase: ^3.2.4
  image_picker: ^1.1.2
  firebase_core: ^3.15.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.7.0
  firebase_storage: ^12.5.0
  google_sign_in: ^6.3.1
  audio_waveforms: ^1.0.5
  intl: ^0.20.3
  cloud_functions: ^5.6.0
  cached_network_image: ^3.3.1
  flutter_slidable: ^3.1.0
  provider: ^6.1.2
  video_player: ^2.8.6
  font_awesome_flutter: ^10.7.1
  
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_ausgefuellt.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/data/traeume_lexikon.json


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic